questions = [
    "Who is the founder of GlowithMartha?",
    "What professional credentials does Martha hold?",
    "When did Martha begin practicing as an esthetician and massage therapist?",
    "Where is the GlowithMartha studio located?",
    "What type of studio is GlowithMartha?",
    "Who currently performs all the services at GlowithMartha?",
    "Why was GlowithMartha created by Martha?",
    "What problems in the beauty industry did Martha notice before founding GlowithMartha?",
    "What is the mission of GlowithMartha?",
    "What is the long-term vision for GlowithMartha?",
    "What does the GlowithMartha brand promise to its clients?",
    "What are the core values of GlowithMartha?",
    "What types of services are offered at GlowithMartha?",
    "How much does a Brazilian waxing service cost at GlowithMartha?",
    "What is the price of full legs waxing?",
    "How much does underarms waxing cost?",
    "What is the cost of eyebrow waxing?",
    "How much does a relaxing 60-minute massage cost?",
    "What are the different types of lash extension services offered?",
    "What is the price of a classic full set of lash extensions?",
    "How much does the hybrid lash extension service cost?",
    "What is the price of volume lash extensions?",
    "How much does a standard facial cost?",
    "What is the price of a mini facial?",
    "What services are included in the 2-hour facial and massage experience package?",
    "How much does the 2-hour facial and massage experience cost?",
    "What add-on service is available for a foot scrub and what is its price?",
    "What happens at the beginning of every client appointment at GlowithMartha?",
    "What common problems do clients report experiencing at other beauty studios?",
    "How does GlowithMartha address painful waxing, rushed services, and unrealistic promises?"
]
